#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.
set -xe

env

source ${OPENSHIFT_HOMEDIR}app-root/runtime/dependencies/python/virtenv/bin/activate

cat ${OPENSHIFT_REPO_DIR}requirements.txt

pip install -r ${OPENSHIFT_REPO_DIR}requirements.txt

# We don't have sentry yet
# python ${OPENSHIFT_REPO_DIR}manage.py raven test

python ${OPENSHIFT_REPO_DIR}manage.py migrate --noinput

pushd ${OPENSHIFT_REPO_DIR}
if ! git log ${OPENSHIFT_REPO_DIR}wsgi/static/stylesheets/libs.min.css; then
    npm install bower
    find . -name bower
    bower install
    npm install
fi
node_modules/gulp/bin/gulp.js less
./manage.py collectstatic --noinput
popd

mkdir -p ${OPENSHIFT_DATA_DIR}media
mkdir -p ${OPENSHIFT_REPO_DIR}wsgi/static/media
ln -sf ${OPENSHIFT_DATA_DIR}media ${OPENSHIFT_REPO_DIR}wsgi/static/media
