sudo: false
env:
  - DJANGO_DEBUG=True DJANGO_SETTINGS_MODULE=memopol.settings
language: python
python:
- '2.7'
before_install:
- pip install codecov
install:
- pip install -e .[testing]
before_script:
- bin/install_client_deps.sh
script:
- bash -c '! lesscpy -N static/less/base.less 2>&1 | grep Error'
- flake8 . --exclude '*/migrations,docs,static' --ignore E128
- py.test memopol representatives_positions representatives_recommendations
- rm -rf db.sqlite
- django-admin migrate
- django-admin update_score
after_success:
- codecov
deploy:
- provider: openshift
  user: jamespic@gmail.com
  password:
    secure: W7hQDKAtmpOfwLjBuss6NEKqPSrRhsbgH8a8eV+/Oo6HZxMi1mbNFSi+6WRNSs3Cil0ZZV+awoqC61jIzV4oTwEYcy5bv9NWNSY1QO34DECMS5sY00wA0zKhkdsdTr9Pc3TLRp1cw6x2KNCF356FKZojFTRbjtfJ79rqBc5k5ww=
  app: master
  domain: memopol
  skip_cleanup: true
  deployment_branch: master
  on:
    repo: political-memory/political_memory
    branch: master
- provider: openshift
  user: jamespic@gmail.com
  password:
    secure: W7hQDKAtmpOfwLjBuss6NEKqPSrRhsbgH8a8eV+/Oo6HZxMi1mbNFSi+6WRNSs3Cil0ZZV+awoqC61jIzV4oTwEYcy5bv9NWNSY1QO34DECMS5sY00wA0zKhkdsdTr9Pc3TLRp1cw6x2KNCF356FKZojFTRbjtfJ79rqBc5k5ww=
  app: lqdn
  domain: memopol
  skip_cleanup: true
  deployment_branch: lqdn
  on:
    repo: political-memory/political_memory
    branch: lqdn
- provider: openshift
  user: jamespic@gmail.com
  password:
    secure: W7hQDKAtmpOfwLjBuss6NEKqPSrRhsbgH8a8eV+/Oo6HZxMi1mbNFSi+6WRNSs3Cil0ZZV+awoqC61jIzV4oTwEYcy5bv9NWNSY1QO34DECMS5sY00wA0zKhkdsdTr9Pc3TLRp1cw6x2KNCF356FKZojFTRbjtfJ79rqBc5k5ww=
  app: pr
  domain: memopol
  skip_cleanup: true
  deployment_branch: pr
  on:
    repo: political-memory/political_memory
    branch: pr
