sudo: false
env:
  matrix:
  - DEBUG=True
language: python
python:
- '2.7'
install:
- pip install django
- pip install -r requirements.txt
before_script:
- npm install -g bower
- bower install
- npm install
script:
- "./manage.py migrate"
- node_modules/gulp/bin/gulp.js less
after_success:
- ./manage.py collectstatic --noinput
- tar cvfj wsgi.tbz2 wsgi
- git config --global user.email "travis@localhost.localdomain"
- git config --global user.name "Travis CI"
- git checkout $TRAVIS_BRANCH
- git add --all
- git commit -am "Travis change"
- git tag -f ${TRAVIS_BRANCH}_build
deploy:
- provider: releases
  api_key:
    secure: cK8VLq7h9mqU0sIdIAaVK3gbEU/jL44nNeFiPAinYTY0WaFAPPUaWSb/g/HsXY1HmT3l551uA0KTTWdLZlXdEjkCKk8tK2+XSYf2F9Al9iMHFH0CoIE8QdXCBmK5KdOBwmx71EDr7238ToMKzkIXmS7S/TVbGSYxJ6qCr/XEHZ8=
  file: wsgi.tar
  on:
    repo: political-memory/political_memory
    all_branches: true
- provider: openshift
  user: jamespic@gmail.com
  password:
    secure: W7hQDKAtmpOfwLjBuss6NEKqPSrRhsbgH8a8eV+/Oo6HZxMi1mbNFSi+6WRNSs3Cil0ZZV+awoqC61jIzV4oTwEYcy5bv9NWNSY1QO34DECMS5sY00wA0zKhkdsdTr9Pc3TLRp1cw6x2KNCF356FKZojFTRbjtfJ79rqBc5k5ww=
  app: dev
  domain: memopol
  skip_cleanup: true
  deployment_branch: openshift
  on:
    repo: political-memory/political_memory
    branch: openshift
