sudo: false
language: python
python:
  - "2.7"
install:
  - pip install django
  - pip install -U pip
  - pip install -r requirements.txt
  - cp memopol/config.json.sample memopol/config.json
before_script:
  - npm install -g bower
  - bower install
script:
  - ./manage.py migrate
  - node_modules/gulp/bin/gulp.js less
