sudo: false
language: python
python:
  - "2.7"
install:
  - pip install django
  - pip install -r requirements.txt
before_script:
  - npm install -g bower
  - bower install
  - npm install
script:
  - ./manage.py migrate
  - node_modules/gulp/bin/gulp.js less
