#!/bin/bash
set -x

source ${OPENSHIFT_HOMEDIR}app-root/runtime/dependencies/python/virtenv/bin/activate
export DJANGO_SETTINGS_MODULE=memopol.settings

pushd ${OPENSHIFT_REPO_DIR}
curl http://parltrack.euwiki.org/dumps/ep_meps_current.json.xz | unxz -c - | parltrack_import_representatives
popd
